# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cajas',
            field=models.ManyToManyField(through='cajadiaria.CajaDiaria', to='cajadiaria.TipoCuenta'),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajadiaria.Cuenta'),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='tipocuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajadiaria.TipoCuenta'),
        ),
    ]
